#!/bin/bash

#Submit this script with: sbatch thefilename

#SBATCH --time=168:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --mem-per-cpu=10G   # memory per CPU core
#SBATCH -J "10Ldamage"   # job name
##SBATCH --mail-user=elifo@caltech.edu


# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load intel/19.1_NEW 
module load python3/3.8.5

# SWITCH TO VIRTUAL ENV
source  /central/groups/enceladus/ELIF/python-environments/my-test-venv/bin/activate

# modify PATH to qdyn in main.py
python main.py
